/* AUTO-GENERATED from content.json + settings.json by build.js — do not edit by hand.
   Edit in the admin dashboard (yoursite.com/admin), or by hand in content.json / settings.json. */
window.SITE_WORKS = [
  {
    "title": "Thala Forever — MS Dhoni Tribute Anthem",
    "drive": "",
    "yt": "GrlAr6Dxfkc",
    "filter": "music",
    "cat": "Music Video · Paid Campaign",
    "chip": "1M+ Views · Featured",
    "big": "THALA",
    "sub": "MS Dhoni Tribute",
    "featured": true,
    "grad": "linear-gradient(135deg,#3a1010 0%,#6a1815 45%,#1a0808 100%)"
  },
  {
    "title": "Independence Day — A Nation in Frames",
    "drive": "1afChECBWrDekeX8ay-R1LsMdbz3x7qXC",
    "yt": "",
    "filter": "cinematic",
    "cat": "Cinematic · Patriotic Film",
    "chip": "Patriotic",
    "big": "INDIA",
    "sub": "A Patriotic Film",
    "featured": false,
    "footCat": "Cinematic · Patriotic",
    "grad": "linear-gradient(135deg,#3a1810 0%,#5a2010 45%,#1a0808 100%)"
  },
  {
    "title": "Peace Song — A Quiet Anthem",
    "drive": "1c_F5eq2TOoUgn4m07Di6JjVgUgMnyL44",
    "yt": "",
    "filter": "music",
    "cat": "Music · Original Track",
    "chip": "Music Video",
    "big": "PEACE",
    "sub": "An Original Song",
    "featured": false,
    "grad": "linear-gradient(135deg,#1a0a08 0%,#2a1812 55%,#3a2418 100%)"
  },
  {
    "title": "Chetan Bhagat — Stories That Shaped Young Minds",
    "drive": "",
    "yt": "36Dbik_VC3A",
    "filter": "cinematic",
    "cat": "Portrait Film · YouTube",
    "chip": "Portrait",
    "big": "CHETAN",
    "sub": "A Portrait in Motion",
    "featured": false,
    "footCat": "Portrait Film · Velammal Nexus",
    "grad": "linear-gradient(135deg,#0a0a18 0%,#181028 55%,#241838 100%)"
  },
  {
    "title": "Velammal Nexus — The Brand Film",
    "drive": "12fq7UnKFztxk4ZXY-r7njkAISXnL_fQO",
    "yt": "",
    "filter": "commercial",
    "cat": "Brand Film",
    "chip": "Brand",
    "big": "NEXUS",
    "sub": "The Brand Film",
    "featured": false,
    "grad": "linear-gradient(135deg,#1a0030 0%,#3d0068 45%,#1a0820 100%)"
  },
  {
    "title": "Velammal Nexus — Full Cut",
    "drive": "1htMaDUwvTNMvRGvzGB_JpRcwB_E8kbAk",
    "yt": "",
    "filter": "commercial",
    "cat": "Brand Film · 4K · 1 min",
    "chip": "Featured · 4K · 1 min",
    "big": "1:00",
    "sub": "4K Brand Film",
    "featured": true,
    "footCat": "Brand Film · Long Form",
    "grad": "linear-gradient(135deg,#180020 0%,#2a0040 55%,#3d1060 100%)"
  },
  {
    "title": "Ashish — Against the Sky · The Everest Summit",
    "drive": "",
    "yt": "xnTyn_zb67s",
    "filter": "cinematic",
    "cat": "Cinematic · Documentary",
    "chip": "Documentary",
    "big": "ASHISH",
    "sub": "A Documentary Film",
    "featured": false,
    "footCat": "Documentary · Velammal Nexus",
    "grad": "linear-gradient(135deg,#180c08 0%,#2a1808 55%,#3c2010 100%)"
  },
  {
    "title": "Gukesh — The King of Chess",
    "drive": "",
    "yt": "x_3rUuYJ-BQ",
    "filter": "music",
    "cat": "Sports AV · Tribute",
    "chip": "Sports AV",
    "big": "GUKESH",
    "sub": "World Champion",
    "featured": false,
    "footCat": "Sports AV · Velammal Nexus",
    "grad": "linear-gradient(135deg,#0a0a18 0%,#101028 55%,#181c38 100%)"
  },
  {
    "title": "Harmanpreet Kaur — Hitting Boundaries, Breaking Barriers",
    "drive": "",
    "yt": "Cw9BLgVV0-g",
    "filter": "music",
    "cat": "Sports AV · Tribute",
    "chip": "Sports AV",
    "big": "HARMAN",
    "sub": "Captain of India",
    "featured": false,
    "footCat": "Sports AV · Velammal Nexus",
    "grad": "linear-gradient(135deg,#180a10 0%,#2a1218 55%,#3a1820 100%)"
  },
  {
    "title": "Usain Bolt — The Man Who Redefined Speed",
    "drive": "",
    "yt": "xjCtuwqQRUQ",
    "filter": "music",
    "cat": "Sports AV · Tribute",
    "chip": "Sports AV",
    "big": "BOLT",
    "sub": "The Sprint",
    "featured": false,
    "footCat": "Sports AV · Velammal Nexus",
    "grad": "linear-gradient(135deg,#001218 0%,#002040 55%,#003858 100%)"
  },
  {
    "title": "Thirty Seconds, Told in 4K",
    "drive": "1GrNAheRl2PIduBFFNae_KYjB3ox1muKi",
    "yt": "",
    "filter": "commercial",
    "cat": "Commercial · Brand Spot",
    "chip": "Featured · 4K Spot",
    "big": ":30",
    "sub": "4K Cinematic Spot",
    "featured": true,
    "grad": "linear-gradient(135deg,#080814 0%,#100c20 55%,#1c142c 100%)"
  },
  {
    "title": "Twenty Seconds, Told in 4K",
    "drive": "1juGrJQHkGThs8YLI7V7XjJsqdOZ0xhJ5",
    "yt": "",
    "filter": "commercial",
    "cat": "Brand Spot",
    "chip": "4K · :20",
    "big": ":20",
    "sub": "4K Brand Spot",
    "featured": false,
    "grad": "linear-gradient(135deg,#0a0a18 0%,#101028 55%,#181c38 100%)"
  },
  {
    "title": "The Mandate — Election Awareness",
    "drive": "1PzY_zXi-v6En8CUnrgYFt_dvVI2maL0l",
    "yt": "",
    "filter": "commercial",
    "cat": "Political · Campaign",
    "chip": "Political",
    "big": "MANDATE",
    "sub": "Election Awareness",
    "featured": false,
    "grad": "linear-gradient(135deg,#180a08 0%,#2a1208 55%,#3a1810 100%)"
  },
  {
    "title": "Every Vote Counts — Campaign Film",
    "drive": "1NhxXhxfAoTARvNsE5l8t1XE0CX5qCUKY",
    "yt": "",
    "filter": "commercial",
    "cat": "Political · Campaign",
    "chip": "Political",
    "big": "VOTE",
    "sub": "Every Vote Counts",
    "featured": false,
    "grad": "linear-gradient(135deg,#180a10 0%,#2a1218 55%,#3a1820 100%)"
  },
  {
    "title": "Margazhi Utsav — TV Spot",
    "drive": "1YoFn04xUdwfonBliu_7TZxJRkG62Xozw",
    "yt": "",
    "filter": "events",
    "cat": "Event · Festival",
    "chip": "Festival TV",
    "big": "UTSAV",
    "sub": "Margazhi · A Festival",
    "featured": false,
    "grad": "linear-gradient(135deg,#180c08 0%,#2a1808 55%,#3c2010 100%)"
  },
  {
    "title": "Many Happy Returns — A Tribute Film",
    "drive": "1tnLwDxOg7wjp7vUmZlwCLidiR2t5leMY",
    "yt": "",
    "filter": "events",
    "cat": "Event · Tribute",
    "chip": "Tribute",
    "big": "RETURNS",
    "sub": "Many Happy",
    "featured": false,
    "grad": "linear-gradient(135deg,#0c0818 0%,#181028 55%,#241838 100%)"
  },
  {
    "title": "Adayalampattu — Campus Walkthrough",
    "drive": "1C7C1CL2XBFc_6cnnS_wMMIXWvcF7tM83",
    "yt": "",
    "filter": "events",
    "cat": "Event · Campus Film",
    "chip": "Featured · Walkthrough",
    "big": "ADAYALAMPATTU",
    "sub": "Campus Walkthrough",
    "featured": true,
    "grad": "linear-gradient(135deg,#0a1208 0%,#142a18 55%,#1c3a28 100%)"
  }
];
window.SITE_SETTINGS = {
  "email": "naveshwara@gmail.com",
  "phone": "+91 80722 53477",
  "phoneHref": "+918072253477",
  "whatsapp": "918072253477",
  "instagram": "",
  "youtube": "",
  "ogImage": ""
};
